# Site settings
name: "Aron Atkins"
title: "Aron Atkins"
email: aron.atkins@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am Aron Atkins, a software engineer and musician living just outside
  Boston.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://aronatkins.github.io" # the base hostname & protocol for your site
twitter_username: aronatkins
github_username:  aronatkins

# Build settings
kramdown:
  input: GFM
  hard_wrap: false

gems:
  - jekyll-feed
