# Site settings
title: firepole
email: aron.atkins@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am Aron Atkins, a software engineer and musician living just outside
  Boston. I studied mathematics and computer science at WPI.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://aronatkins.github.io" # the base hostname & protocol for your site
twitter_username: aronatkins
github_username:  aronatkins

# Build settings
markdown: kramdown
